name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: Exposed Internals

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup environment
        id: setup_env
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PLUGIN_REPO=$(basename ${{ github.repository }})
          PLUGIN_AUTHOR="${{ github.repository_owner }}"
          PLUGIN_AUTHORURL="https://github.com/${PLUGIN_AUTHOR}/${PLUGIN_REPO}"
          PLUGIN_VERSION=${{ github.ref_name }}
          PLUGIN_DESCRIPTION=$(gh repo view "${PLUGIN_AUTHOR}/${PLUGIN_REPO}" --json description --jq .description)
          PLUGIN_LICENSE=$(gh repo view "${PLUGIN_AUTHOR}/${PLUGIN_REPO}" --json licenseInfo '.licenseInfo.spdxId')
          PLUGIN_ID=${PLUGIN_REPO#obsidian-}
          PLUGIN_MINAPPVERSION="1.0.0"
          echo "PLUGIN_REPO=${PLUGIN_REPO}" >> $GITHUB_ENV
          echo "PLUGIN_AUTHOR=${PLUGIN_AUTHOR}" >> $GITHUB_ENV
          echo "PLUGIN_AUTHROURL=${PLUGIN_AUTHORURL}" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=${PLUGIN_VERSION}" >> $GITHUB_ENV
          echo "PLUGIN_DESCRIPTION=${PLUGIN_DESCRIPTION}" >> $GITHUB_ENV
          echo "PLUGIN_LICENSE=${PLUGIN_LICENSE}" >> $GITHUB_ENV
          echo "PLUGIN_ID=${PLUGIN_ID}" >> $GITHUB_ENV
          echo "PLUGIN_MINAPPVERSION=${PLUGIN_MINAPPVERSION}" >> $GITHUB_ENV

      - name: Generate manifest.json
        run: |
          jq -n \
            --arg name "${{ env.PLUGIN_NAME }}" \
            --arg repo = ${PLUGIN_REPO} \
            --arg author "${PLUGIN_AUTHOR}" \
            --arg authorUrl "{$PLUGIN_AUTHORURL}" \
            --arg version "${PLUGIN_VERSION}" \
            --arg description "${PLUGIN_DESCRIPTION}" \
            --arg license "${PLUGIN_LICENSE}" \
            --arg id "${PLUGIN_ID}" \
            --arg minAppVersion ${PLUGIN_MINAPPVERSION}" \
            --argjson isDesktopOnly true \
            '{
              id: $id,
              name: $name,
              author: $author,
              authorUrl: $authorUrl,
              version: $version,
              description: $description,
              isDesktopOnly: $isDesktopOnly
            }' > manifest.json

      - name: Populate package.json
        run: |
          jq \
            --arg name "${PLUGIN_NAME}" \
            --arg repo = ${PLUGIN_REPO} \
            --arg author "${PLUGIN_AUTHOR}" \
            --arg authorUrl "{$PLUGIN_AUTHORURL}" \
            --arg version "${PLUGIN_VERSION}" \
            --arg description "${PLUGIN_DESCRIPTION}" \
            --arg license "${PLUGIN_LICENSE}" \
            --arg id "${PLUGIN_ID}" \
            --arg minAppVersion ${PLUGIN_MINAPPVERSION}" \
            package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Build plugin
        id: build
        run: |
          npm install
          npm run build
          mkdir ${PLUGIN_ID}
          cp dist/main.js dist/manifest.json ${PLUGIN_ID}
          zip -r ${PLUGIN_ID}.zip ${PLUGIN_ID}

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/main.js dist/manifest.json dist/styles.css ${{ env.PLUGIN_NAME }}.zip
